name: erasmus_connect
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_drawing: ^1.0.0
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.4
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.1.2
  animations: ^2.0.7

  # figma:
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  pin_code_fields: ^7.3.0
  intl: ^0.18.0
  chat_gpt_sdk: 2.0.2
  scroll_snap_list: ^0.9.1
  url_launcher: ^6.1.11
  intl_phone_field: ^3.2.0
  searchfield: ^0.8.3
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/UrbanistRomanBold.ttf
          weight: 700
        - asset: assets/fonts/UrbanistRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/UrbanistRomanThin.ttf
          weight: 100
        - asset: assets/fonts/UrbanistRomanSemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300
    - family: Intern
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
